{"name": "Verify login with invalid combinations of email and password -- @1.3 ", "status": "failed", "statusDetails": {"message": "AssertionError: AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'\n", "trace": "  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"OpenCartDemoSimulation\\features\\steps\\login_steps.py\", line 49, in step_impl\n    assert \"Warning: No match for E-Mail Address and/or Password.\" in context.login_page.get_login_error(), f\"AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got '{context.login_page.get_login_error()}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I open the OpenCart login page", "status": "passed", "start": 1745240423660, "stop": 1745240424640}, {"name": "When I enter email \"EMPTY\" and password \"EMPTY\" in the login form", "status": "passed", "start": 1745240424640, "stop": 1745240424930}, {"name": "And I submit the login form", "status": "passed", "start": 1745240424931, "stop": 1745240425129}, {"name": "Then I should see an error message saying \"Warning: No match for E-Mail Address and/or Password.\"", "status": "failed", "statusDetails": {"message": "AssertionError: AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'\n", "trace": "  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"OpenCartDemoSimulation\\features\\steps\\login_steps.py\", line 49, in step_impl\n    assert \"Warning: No match for E-Mail Address and/or Password.\" in context.login_page.get_login_error(), f\"AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got '{context.login_page.get_login_error()}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1745240425129, "stop": 1745240425763}], "parameters": [{"name": "email", "value": "EMPTY"}, {"name": "password", "value": "EMPTY"}], "start": 1745240421017, "stop": 1745240428051, "uuid": "eda275f2-6508-425d-b66b-3da8bc3758d8", "historyId": "bc1e0164b8efb7727aff867693479899", "fullName": "User Authentication: Verify login with invalid combinations of email and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "browser"}, {"name": "feature", "value": "User Authentication"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}